name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        - name: Use Node.js 10.x
        uses: actions/setup-node@v1
         with:
          node-version: 10.x
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
      - name: npm install, build
        run: |
          cd site
          npm install
          npm run build
      - name: Default test
        uses: percy/snapshot-action@v0.1.1
        with:
          build-directory: "percy-test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
