name: CI
on: [push, pull_request]
  jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
            PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        with:
          working-directory: packages/web-take-action
          build: npm run build
          start: npx http-server ./dist
          wait-on: http://localhost:8080

