name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
      - name: npm install, build
        run: |
          cd percy-test
          npm install
       - name: Percy Test
         uses: percy/storybook-action@v0.1.2
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          