name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: npm install, build
        run: |
          cd percy-test
          npm install
          npm run build
      - name: Percy test
        uses: percy/exec-action@master
        with:
          build-directory: "./percy-test"
          command: "node snapshots.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
