name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: npm install, build
        run: |
          cd percy-test
          npm install
          npm run build
       - name: Default test
        uses: percy/snapshot-action@v0.1.1
        with:
          build-directory: "./percy-test/dist"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
