
name: CI
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: percy/exec-action@v0.3.0
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        with:
          command: "npx cypress run" 
          working-directory: percy-test
          build: npm run build
          start: npx http-server ./dist
          wait-on: http://localhost:8080
