name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
      - name: npm install, build
        run: |
          cd percy-test
          npm install
          npm run build
      - name: Default test
        run: | 
        npm install -D @percy/script
        percy/snapshot-action@v0.1.1
       - with:
          build-directory: "./"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
